/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
  val greeting: String
    get() {
      return "This is the server, welcome. It will expose GRPC endpoints."
    }
}

fun main() {
  println(App().greeting)
}
